source 'https://rubygems.org'

ruby "2.2.3"

gem 'bundler'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'
# Use Postgres as the database for Active Record
gem 'pg'
gem 'mysql2', '~> 0.3.18'
# Use SCSS for stylesheets
gem 'bootstrap-sass', '~> 3.3.6'
gem 'sass-rails' #, '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby
# [Helio] these gems are 6x faster than therubyracer for this probject
# Need to ensure compatibility before start using it
# gem 'execjs', github: 'rails/execjs'
# gem 'mini_racer'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'pry'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'bullet'
  gem 'ruby-prof'
end

group :development, :test, :print do
  # gem 'cupsffi'
end

group :development, :test, :staging do
  gem 'yaml_db'
end

group :print, :production do
  gem 'fast_blank'
end

gem 'activeadmin', '~> 1.0.0.pre1'
gem 'devise'
gem 'cancancan'
gem 'rolify'
gem 'swagger-docs'
gem 'jwt'

gem 'rails_12factor', group: :heroku
gem 'rack-cors', :require => 'rack/cors'
gem 'nokogiri'
gem 'rmagick', '2.13.4'
gem 'mini_magick'

gem 'capybara'
gem 'poltergeist'
# gem 'capybara/dsl'
# gem 'capybara/poltergeist'

gem 'foreman'
gem 'puma'
gem 'delayed_job_active_record'
gem 'carrierwave'
gem 'mustache'
gem 'ffi'
gem 'simple_enum'
gem 'wash_out'
gem 'fog' #, '~> 1.3.1'
gem 'country_select'
gem 'paper_trail', '~> 4.0.0.rc'
gem 'money-rails'

gem 'rqrcode_png'
gem 'barby'

gem 'dotenv-rails'
gem 'aws-sdk', '~> 2'
gem 'newrelic_rpm'
gem 'savon'

gem 'bootsy'
# gem 'wicked_pdf'
# gem 'wkhtmltopdf-binary'
gem 'mailgun-ruby', '~>1', require: 'mailgun'
gem 'spreadsheet'
gem 'select2-rails'
